/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as RegisterRouteImport } from './routes/register'
import { Route as LoginRouteImport } from './routes/login'
import { Route as CreateMonsterRouteImport } from './routes/create-monster'
import { Route as IndexRouteImport } from './routes/index'
import { Route as MonsterIdRouteImport } from './routes/monster.$id'

const RegisterRoute = RegisterRouteImport.update({
  id: '/register',
  path: '/register',
  getParentRoute: () => rootRouteImport,
} as any)
const LoginRoute = LoginRouteImport.update({
  id: '/login',
  path: '/login',
  getParentRoute: () => rootRouteImport,
} as any)
const CreateMonsterRoute = CreateMonsterRouteImport.update({
  id: '/create-monster',
  path: '/create-monster',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const MonsterIdRoute = MonsterIdRouteImport.update({
  id: '/monster/$id',
  path: '/monster/$id',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/create-monster': typeof CreateMonsterRoute
  '/login': typeof LoginRoute
  '/register': typeof RegisterRoute
  '/monster/$id': typeof MonsterIdRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/create-monster': typeof CreateMonsterRoute
  '/login': typeof LoginRoute
  '/register': typeof RegisterRoute
  '/monster/$id': typeof MonsterIdRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/create-monster': typeof CreateMonsterRoute
  '/login': typeof LoginRoute
  '/register': typeof RegisterRoute
  '/monster/$id': typeof MonsterIdRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths: '/' | '/create-monster' | '/login' | '/register' | '/monster/$id'
  fileRoutesByTo: FileRoutesByTo
  to: '/' | '/create-monster' | '/login' | '/register' | '/monster/$id'
  id:
    | '__root__'
    | '/'
    | '/create-monster'
    | '/login'
    | '/register'
    | '/monster/$id'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  CreateMonsterRoute: typeof CreateMonsterRoute
  LoginRoute: typeof LoginRoute
  RegisterRoute: typeof RegisterRoute
  MonsterIdRoute: typeof MonsterIdRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/register': {
      id: '/register'
      path: '/register'
      fullPath: '/register'
      preLoaderRoute: typeof RegisterRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/login': {
      id: '/login'
      path: '/login'
      fullPath: '/login'
      preLoaderRoute: typeof LoginRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/create-monster': {
      id: '/create-monster'
      path: '/create-monster'
      fullPath: '/create-monster'
      preLoaderRoute: typeof CreateMonsterRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/monster/$id': {
      id: '/monster/$id'
      path: '/monster/$id'
      fullPath: '/monster/$id'
      preLoaderRoute: typeof MonsterIdRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  CreateMonsterRoute: CreateMonsterRoute,
  LoginRoute: LoginRoute,
  RegisterRoute: RegisterRoute,
  MonsterIdRoute: MonsterIdRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
